# Arrays

Durante esta sección vamos a trabajar con el tipo de datos "array", aprendiendo como podemos generarlos, recorrerlos, consultarlos, etc. 

## Lección 1 - Creación de arrays

### La clase de objetos array
Un array es una estructura de datos de un mismo tipo organizada en forma de tabla o cuadrícula de distintas dimensiones.

Las dimensiones de un array también se conocen como ejes.
<img src=https://aprendeconalf.es/docencia/python/manual/img/arrays.png>

In [2]:
import numpy as np

### Creación de arrays
Para crear un array se utiliza la siguiente función de NumPy

- `np.array(lista)` : Crea un array a partir de la lista o tupla lista y devuelve una referencia a él. El número de dimensiones del array dependerá de las listas o tuplas anidadas en lista:

- Para una lista de valores se crea un array de una dimensión, también conocido como **vector**.

- Para una lista de listas de valores se crea un array de dos dimensiones, también conocido como **matriz**.

- Para una lista de listas de listas de valores se crea un array de tres dimensiones, también conocido como **cubo**.

- Y así sucesivamente. No hay límite en el número de dimensiones del array más allá de la memoria disponible en el sistema.

Los elementos de la lista o tupla deben ser del mismo tipo.

In [ ]:
#Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)

In [ ]:
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

In [ ]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)
a3.shape

Un ***ndarray*** es un conjunto multidimensional (generalmente de tamaño fijo) de elementos del mismo tipo y tamaño. El número de dimensiones y elementos en una matriz se define por su forma, que es una tupla de N números enteros no negativos que especifican los tamaños de cada dimensión. El tipo de elementos de la matriz se especifica mediante un objeto de tipo de datos independiente (dtype), uno de los cuales está asociado con cada ndarray.

El constructor a bajo nivel de **ndarray** es *np.ndarray*, pero no se recomienda su uso. Para la creación de arrays, se recomienda usar los métodos:
- [array](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array): Construye un nuevo array
- [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros): Construye un array de zeros
- [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones): Construye un array vacío

Vamos a usar dichos métodos para crear nuevos arrays.

El parámetro `dtype` en Python, es muy útil cuando trabajamos con **arrays** de **NumPy** y **pandas** para especificar el tipo de datos.

<img src=https://numpy.org/doc/stable/_images/threefundamental.png>

En la imagen anterior se ilustra el funcionamiento de `dtype`. Los componentes que puedes observar son: ndarray, header y head. 
- `ndarray`: esta es la representación de un array, en donde podemos ver las partes que lo componen. A grandes rasgos tenemos el encabezamiento (*header*) y un conjunto de cuadros que representan una serie de elementos contenidos en el array.
- `header`: O encabezado, al principio del ndarray es una estructura de datos que contiene información crucial sobre el array. Específicamente:
  -  Información sobre la forma (shape): las dimnensiones y el tamaño de la dimensión.
  -  Información sobre el tipo de datos (dtype): el tipo de datos contiene (int, float, str, etc.) y el tamaño en bytes de cada elemento.
  -  Información sobre el stride: el número de bytes que hay que saltar en memoria para ir al siguiente elemento.
  -  Flags y metadatos adicionales: si el array es continuo en memoria, si es de solo lectura, etc
- `head`: es como el "cerebro" del array que contiene toda la información necesaria para manejar y acceder a los datos. Nos podemos imaginar que es como la etiqueta de un producto que te dice todas sus características importantes.

Otras funciones útiles que permiten generar arrays son:

- `np.empty(dimensiones)` : Crea y devuelve una referencia a un array vacío con las dimensiones especificadas en la tupla dimensiones.

- `np.zeros(dimensiones)` : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son todos ceros.

- `np.ones(dimensiones)` : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son todos unos.

- `np.full(dimensiones, valor)` : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son todos valor.

- `np.identity(n)` : Crea y devuelve una referencia a la matriz identidad de dimensión n.

- `np.arange(inicio, fin, salto)` : Crea y devuelve una referencia a un array de una dimensión cuyos elementos son la secuencia desde inicio hasta fin tomando valores cada salto.

- `np.linspace(inicio, fin, n`) : Crea y devuelve una referencia a un array de una dimensión cuyos elementos son la secuencia de n valores equidistantes desde inicio hasta fin.

- `np.random.random(dimensiones)` : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son aleatorios.

In [ ]:
print(np.zeros(3,2))

In [ ]:
print(np.idendity(3))

In [ ]:
print(np.arange(1, 10, 2))

In [ ]:
print(np.linspace(0, 10, 5))

#### array

In [ ]:
array1 = np.array([1,2,3,4,5,6], dtype = 'int')
print(type(array1))
array1

In [ ]:
array2 = np.array([[1,2,3],[4,5,6]], dtype = 'int', ndmin=2 )
array2

In [ ]:
array3 = np.array([1,2,3], dtype = 'complex')
array3

#### zeros

In [ ]:
np.zeros(10)

In [ ]:
np.zeros((5,2))

#### ones

In [ ]:
np.ones(10)

In [ ]:
np.ones((5,2))

#### range

In [ ]:
a = np.arange(10)
a

### Atributos de un array
Existen varios atributos y funciones que describen las características de un array.

- `a.ndim` : Devuelve el número de dimensiones del array a.

- `a.shape` : Devuelve una tupla con las dimensiones del array a.

- `a.size` : Devuelve el número de elementos del array a.

- `a.dtype`: Devuelve el tipo de datos de los elementos del array a.

- `a.reshape`: Permite cambiar la forma de una matriz sin cambiar los datos.
Un ejemplo:

In [ ]:
a.reshape((2,5))

## 1 - Tipos de datos

In [ ]:
import numpy as np

Python define solo un tipo por cadaclase de datos en particular (solo hay un tipo de entero, un tipo de float, etc.). Esto puede tener sentido en aplicaciones que no necesitan preocuparse por las distintas formas en en que se pueden representar los datos en un ordenador. Sin embargo, cuando trabajamos con el análisis de datos, a menudo necesitamos más control. 

En NumPy, hay 24 nuevos tipos fundamentales de Python para describir diferentes tipos de escalares. Estos descriptores de tipo se basan principalmente en los tipos disponibles en el lenguaje C en el que está escrito CPython, con varios tipos adicionales compatibles con los tipos de Python.

Los diferentes tipos de datos están organizados de manera jerárquica como representa la siguiente figura:

<img src=https://numpy.org/doc/stable/_images/dtype-hierarchy.png>
Copyright 2008-2024, NumPy Desarrolladores

In [ ]:
a = np.array([1,2,3,4], dtype=np.int_)
a

In [ ]:
bool_array = np.array([[1,0,0,1], [0,1,1,0]], dtype = np.bool_)
bool_array

In [ ]:
char_array = np.array(['a','b','c'], dtype = np.chararray)
char_array

Además, cada uno de los tipos de la jerarquía que vemos arriba, poseen tipos de datos con distinto tamaño. Esto significa, capaces de almacenar un número distinto de bits. Por ejemplo: 

Para los ***int*** tenemos:
- int8 &rarr; Máximo 8 bits (256)
- int16 &rarr; Máximo 16 bits (65536)
- int32 &rarr; Máximo 32 bits (4294967296)
- int64 &rarr; Máximo 64 bits (18446744073709551616)

Para los ***float*** tenemos:
- float16 &rarr; Máximo 16 bits
- float32 &rarr; Máximo 32 bits
- float64 &rarr; Máximo 64 bits

Te recuerdo qué es un FLOAT de 16 bits.
Se compone de 3 partes:

    Signo (1 bit)
    Exponente (5 bits)
    Mantisa/Fracción (10 bits)

El float16 es útil cuando:

    Necesitas ahorrar memoria
    La precisión extrema no es crítica
    Trabajas con hardware especializado (como GPUs)
    Procesas grandes cantidades de datos

Sin embargo, ten en cuenta que tiene menor precisión que float32 o float64. Ejemplos.

Podéis encontrar todos los tipos de datos en el siguiente [enlace](https://numpy.org/doc/stable/reference/arrays.scalars.html#built-in-scalar-types)

El siguiente trozo de código muestra el tamaño de los tipos `ndarray` dependiendo de si los elementos contenidos pertenecen a un entero de 8 bytes o a un entero de 64 bytes.


In [ ]:
from sys import getsizeof

a = np.array([1,2,3,4], dtype = np.int8)
b = np.array([1,2,3,4], dtype = np.int64)

print("A", getsizeof(a))
print("B", getsizeof(b))

Podemos consultar el tipo de datos de un array con el método *dtype*

In [ ]:
print(a.dtype)
print(b.dtype)

#print(bool_array.dtype)

In [ ]:
dt = np.dtype('int32')
print(dt.type)
dt.type is np.int32

Además, podemos crear tipos de datos con una combinación de '**carácter**' + '**nº de bytes**'. Los carácteres que podemos usar son:

- '?' : boolean
- 'b' : (signed) byte
- 'B' : unsigned byte
- 'i' : (signed) integer
- 'u' : unsigned integer
- 'f' : floating-point
- 'c' : complex-floating point
- 'm' : timedelta
- 'M' : datetime
- 'O' : (Python) objects
- 'S', 'a' : zero-terminated bytes (not recommended)
- 'U' : Unicode string
- 'V' : raw data (void)

In [ ]:
dt = np.dtype('f8')
a = np.array([1,2,3,4], dtype = dt)
print(a)
print(a.dtype)

In [ ]:
dt = np.dtype('int32')
dt.kind   #Identifica el tipo general de dato devolviendo el caracter que lo representa.

Un tipo de dato muy importante en Numpy es el **NaN**, o valor nulo.

In [ ]:
nan = np.nan
np.isnan(nan)

In [ ]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x

#### El tipo matrix

Los objetos de matriz heredan del ndarray y, por lo tanto, tienen los mismos atributos y métodos que ndarrays. Sin embargo, las matrices solo pueden tener dimensión 2. 

In [ ]:
m = np.matrix('1 2 3 ; 4 5 6')
m

In [ ]:
m = np.mat([[1,2,3], [3,4,5]], dtype = np.float16)
len(m)

In [ ]:
a = np.array([[[1,2,3], [3,4,5]],[[6,7,8], [9,10,11]]], dtype = np.float16)
print(type(a))
m = np.asmatrix(a)
print(type(m))
m

## 2 - Indexado y recorrido de arrays

Podemos consultar un campo del array con los carácteres []. Tenemos que recordar que en python, los indices comienzan por cero, por lo que si queremos consultar el primer elemento de un array lo haríamos de la siguiente manera

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[9])
print(a.shape)
print(a[9])

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
print(a)
print(a[1, 0])  # Acceso al elemento de la fila 1 columna 0
print(a[1][0])  # Otra forma de acceder al mismo elemento

[[1 2 3]
 [4 5 6]
 [7 8 9]]
4
4


In [7]:
print(a[:, 0:2])

[[1 2]
 [4 5]
 [7 8]]


### Slicing

Podemos consultar distintos elementos del array con el slicing. En el slice tenemos que definir: *inicio:fin:paso*

In [9]:
print(a)
print('--------')
print(a[0:9:2])
print('--------')
print(a[0:8:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------
[[1 2 3]
 [7 8 9]]
--------
[[1 2 3]]


Podemos recuperar los dos últimos elementos, usando valores negativos

In [10]:
a[-2:10] # Recuerda que de esta manera podemos recuperar las últimas filas del array.

array([[4, 5, 6],
       [7, 8, 9]])

También podemos recorrer los valores de mayor a menor definiendo el tamaño del paso como un nº negativo

In [11]:
a[9::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

También podemos definir solo el inicio, o el fin

In [ ]:
a[:5]

In [ ]:
a[5:]

Para los array multidimensionales funciona del mismo modo. Solo tenemos que verlos en forma de matriz, y consultar la fila y columna que deseemos.

In [ ]:
a = np.array([[1,2,3], [3,4,5]], dtype = np.int8)
a

In [ ]:
a[1][0]

In [ ]:
a[1,0]

In [ ]:
a[1, 0:2]

In [ ]:
a[0:2, 0:2]

Exactamente igual funciona cuando hablamos de un tipo matrix

In [ ]:
print(type(m))
m

In [ ]:
m[0]

In [ ]:
m[0,1] + m[0,0]

En la lección anterior conocimimos el tipo nan. También podemos consultar este tipo de dato.

In [ ]:
x = np.array([[4, 3], [np.nan, 2.], [np.nan, np.nan]])
print(x[x > 3])
print(x[np.isnan(x)])
print(x[~np.isnan(x)])

### Indexado booleano

El indexado booleano en NumPy permite seleccionar elementos de un array según un conjunto de condiciones booleanas. Esto se logra mediante la creación de una máscara booleana, que es un array que contiene valores True o False que se utilizan para filtrar los elementos del array original.

#### Creación de una máscara booleana
Puedes crear una máscara booleana de varias maneras:

1. Comparando un array con un valor escalar, en el siguiente ejemplo:

In [26]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
mask = a > 4

Crea una máscara booleana con valores True para elementos > 4 y False en otro caso.

2. Comparando dos arrays:

In [14]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([2, 3, 4, 5, 6])
mask = a1 > a2

array([False, False, False, False, False])

### Filtrado de elementos de un array
Una característica muy útil de los arrays es que es muy fácil obtener otro array con los elementos que cumplen una condición.

- `a[condicion]` : Devuelve una lista con los elementos del array a que cumplen la condición condicion.

In [27]:
a[mask]

array([5, 6, 7, 8, 9])

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6]])
mask = a % 2 == 0
print(a[mask])

[2 4 6]


In [31]:
mask = (a % 2 == 0)  &  (a > 2)
print(mask)
print(a[mask])

[[False False False]
 [ True False  True]]
[4 6]


Veamos otro ejemplo

In [ ]:
bool_array = np.array([True, False, True, False, True, False, True, False, True, False])
print(a[bool_array[0:2]])

También actuamos de la misma forma cuando el array es de tipo char

In [15]:
char_array = np.array(['Openwebinars', 'Machine Learning', 'Numpy'])
char_array

array(['Openwebinars', 'Machine Learning', 'Numpy'], dtype='<U16')

In [16]:
char_array[char_array == 'Numpy']

array(['Numpy'], dtype='<U16')

### Recorrido

El iterador `nditer` de NumPy es un objeto que permite recorrer los elementos de una o más matrices de forma sistemática. Fue introducido en NumPy 1.6 y proporciona muchas formas flexibles de visitar todos los elementos de una matriz.

In [32]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

for valor in a:
    print(valor)

0
1
2
3
4
5
6
7
8
9


La tarea más básica que se puede realizar con el `nditer` es visitar cada elemento de una matriz. Cada elemento se proporciona uno por uno mediante la interfaz de iterador estándar de Python.
Vamos a usar ahora el iterador `nditer`.

In [39]:
for valor in np.nditer(a):
    print(valor, end=' ')

0 1 2 3 4 5 6 7 8 9 

**¡¡¡El siguiente ejemplo, va a dar un error!!!**

In [38]:
a = np.arange(10).reshape(2,5)
for x in np.nditer(a):
    print(x, end=' ')
    #print(x)

0 1 2 3 4 5 6 7 8 9 

## 4 - Mascaras

En muchas circunstancias, los conjuntos de datos pueden estar incompletos o contaminados por la presencia de datos no válidos. Por ejemplo, es posible que un sensor no haya podido registrar datos o haya registrado un valor no válido. El módulo **numpy.ma** proporciona una forma conveniente de abordar este problema mediante la introducción de matrices enmascaradas.

Una matriz enmascarada es la combinación de un *numpy.ndarray* estándar y una máscara. Cuando un elemento de la máscara es *False*, el elemento correspondiente de la matriz asociada es válido y se dice que está desenmascarado. Cuando un elemento de la máscara es *True*, se dice que el elemento correspondiente de la matriz asociada está enmascarado (no válido).

Explicado por el Instituto Astrofísico de Canarias. 

Link: http://research.iac.es/sieinvens/python-course/numpy.html

In [40]:
import numpy.ma as ma

In [41]:
x = np.array([1,2,3,-1,4])

In [42]:
# Definimos el valor negativo como invalido
mask_array = ma.masked_array(x, mask = [0,0,0,1,0])

In [48]:
mask_array

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [44]:
mask_array.min()

1

También podemos definir la máscara directamente en el constructor de array del modulo ma.

In [49]:
x = ma.array([1,2,3,-1,4], mask = [0,0,0,1,0])
x

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

Si queremos recuperar únicamente los valores válidos, usamos el método *compressed*

In [50]:
x.compressed()

array([1, 2, 3, 4])

Puedo enmascarar o desenmascarar todos los elementos asignando True o False a toda la máscara.

In [51]:
x.mask = True
x

masked_array(data=[--, --, --, --, --],
             mask=[ True,  True,  True,  True,  True],
       fill_value=999999,
            dtype=int64)

In [52]:
x.mask = False
x

masked_array(data=[1, 2, 3, -1, 4],
             mask=[False, False, False, False, False],
       fill_value=999999)

Volvemos a como lo teníamos antes:

In [54]:
x.mask = [0,0,0,1,0]
x

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

Podemos consultar si un valor es válido con el método *ma.masked*

In [56]:
print(x[0] is ma.masked)
print(x[3] is ma.masked)

False
True


Podemos 'rellenar' los valores enmascarados con un valor concreto.

In [55]:
x.filled(0)

array([1, 2, 3, 0, 4])

Algunos métodos interesantes para la gestión de máscaras son:

In [57]:
x = np.array([1,2,3,-1,4])
x

array([ 1,  2,  3, -1,  4])

In [58]:
masked = ma.masked_equal(x, 4)
masked

masked_array(data=[1, 2, 3, -1, --],
             mask=[False, False, False, False,  True],
       fill_value=4)

In [59]:
masked = ma.masked_not_equal(x, 2)
masked

masked_array(data=[--, 2, --, --, --],
             mask=[ True, False,  True,  True,  True],
       fill_value=999999)

In [ ]:
masked = ma.masked_where(x<2, x)
masked

In [60]:
masked = ma.masked_greater_equal(x, 2)
masked

masked_array(data=[1, --, --, -1, --],
             mask=[False,  True,  True, False,  True],
       fill_value=999999)

In [61]:
masked = ma.masked_inside(x, 1, 3)
masked

masked_array(data=[--, --, --, -1, 4],
             mask=[ True,  True,  True, False, False],
       fill_value=999999)

## Lección 5 - Trabajando con fechas

A partir de NumPy 1.7, existen tipos de datos de matriz central que admiten de forma nativa la funcionalidad de fecha y hora. El tipo de datos se llama "datetime64", así llamado porque "datetime" ya está usado por una librería nativa de Python.

La forma más básica de crear fechas y horas es a partir de cadenas en formato de fecha o fecha y hora ISO 8601.  Las unidades de fecha son años ('Y'), meses ('M'), semanas ('W') y días ('D'), mientras que las unidades de tiempo son horas ('h'), minutos ('m' ), segundos ('s'), milisegundos ('ms'). 

In [ ]:
import numpy as np

In [ ]:
# Orden: año - mes - dia
d = np.datetime64('2020-09-01')
d

In [ ]:
d = np.datetime64('2020-13-01')
d

In [ ]:
dh = np.datetime64('2020-09-01T14:30')
dh

Podemos crear arrays de fechas, pero debemos indicar el tipo de dato. En otro caso, aparecerá como tipo cadena.

In [ ]:
np.array(['2020-07-01', '2020-08-01', '2020-09-01'])

In [ ]:
np.array(['2020-07-01', '2020-08-01', '2020-09-01'], dtype='datetime64')

También podemos crear arrays de fechas con el iterador de numpy ***arange***

In [62]:
np.arange('2020-08', '2020-09', dtype='datetime64[D]')

array(['2020-08-01', '2020-08-02', '2020-08-03', '2020-08-04',
       '2020-08-05', '2020-08-06', '2020-08-07', '2020-08-08',
       '2020-08-09', '2020-08-10', '2020-08-11', '2020-08-12',
       '2020-08-13', '2020-08-14', '2020-08-15', '2020-08-16',
       '2020-08-17', '2020-08-18', '2020-08-19', '2020-08-20',
       '2020-08-21', '2020-08-22', '2020-08-23', '2020-08-24',
       '2020-08-25', '2020-08-26', '2020-08-27', '2020-08-28',
       '2020-08-29', '2020-08-30', '2020-08-31'], dtype='datetime64[D]')

In [ ]:
np.arange('2020-08', '2020-09', dtype='datetime64[W]')

También podemos realizar comparaciones entre los tipos fechas. Si dos fechas y horas tienen unidades diferentes, es posible que sigan representando el mismo momento de tiempo, y la conversión de una unidad más grande como meses a una unidad más pequeña como días se considera un elenco "seguro" porque el momento del tiempo todavía se representa exactamente.

In [ ]:
np.datetime64('2020') == np.datetime64('2020-01-01')

In [ ]:
np.datetime64('2020-03-14T11') == np.datetime64('2020-03-14T11:00:00.00')

### Operaciones con fechas

NumPy permite la resta de dos valores de fecha y hora, una operación que produce un número con una unidad de tiempo. Para ello, se crea el tipo ***timedelta64***, el cual usa los mismos carácteres de 'Y', 'M', 'D', 'h', 'm', 's' para su creación

In [ ]:
np.timedelta64(4, 'D')

In [ ]:
np.timedelta64(10, 'h')

También podemos generar un timedelta, y luego cambiar su unidad.

In [ ]:
a = np.timedelta64(8, 'D')
np.timedelta64(a, 'W')

Cuando restamos dos fechas, también obtenemos un timedelta64 como resultado

In [ ]:
np.datetime64('2020-08-01') - np.datetime64('2020-07-01')

In [ ]:
# Suma de dias / meses / semanas / etc. a una fecha

np.datetime64('2020-08-01') + np.timedelta64(10, 'D')

In [ ]:
np.datetime64('2020-08-01') - np.timedelta64(1, 'W')

In [ ]:
np.datetime64('2020-08-01') + np.timedelta64(48, 'h')

También podemos realizar operaciones directamente entre dos timedeltas distintos

In [ ]:
np.timedelta64(1, 'W') + np.timedelta64(4, 'D')

Hay dos unidades timedeltas ('Y', años y 'M', meses) que se tratan de manera especial, porque el tiempo que representan cambia dependiendo de cuándo se utilizan. Si bien una unidad de día timedelta equivale a 24 horas, no hay forma de convertir una unidad de mes en días, porque los diferentes meses tienen diferentes números de días.

In [ ]:
a = np.timedelta64(1, 'M')
np.timedelta64(a, 'D')

### Días laborables

Para permitir que la fecha y hora se use en contextos donde solo ciertos días de la semana son válidos, NumPy incluye un conjunto de funciones de “día laborable” (día laboral). El valor predeterminado para las funciones de día laborable es que los únicos días válidos son de lunes a viernes (los días hábiles habituales). La implementación se basa en una "máscara de semana" que contiene 7 banderas booleanas para indicar días válidos

In [ ]:
# 2020-09-03 --> Jueves
np.busday_offset('2020-09-03', 1)

In [ ]:
np.busday_offset('2020-09-03', 2)

Si el día es no laborable, debemos indicar si queremos el siguiente día laborable, o el anterior. Podemos hacerlo con el parámetro *roll*

In [ ]:
np.busday_offset('2020-09-05', 0)

In [ ]:
np.busday_offset('2020-09-05', 0, roll = 'forward')

In [ ]:
np.busday_offset('2020-09-05', 0, roll = 'backward')

Para comprobar si un día es laborable, usamos la funcion ***np.is_busday***

In [ ]:
# Jueves
print(np.is_busday(np.datetime64('2020-09-03')))
# Sabado
print(np.is_busday(np.datetime64('2020-09-05')))

También podemos contar el número de días laborables en un rango de fechas

In [ ]:
np.busday_count(np.datetime64('2020-09-01'), np.datetime64('2020-09-30'))

## Leccion 6 - Constantes

Numpy incluye algunas constantes 

In [ ]:
# Valor infinito positivo
np.inf

In [ ]:
np.inf + np.inf

In [ ]:
# Valor infinitov negativo
np.NINF

In [ ]:
np.isinf(np.NINF)

In [ ]:
np.isposinf(np.NINF)

In [ ]:
np.NINF + np.inf

In [ ]:
np.log(0)

In [ ]:
# NAN - Not a Number
np.nan

In [ ]:
# Valor cero negativo
np.NZERO

In [ ]:
# Valor cero positivo
np.PZERO

In [ ]:
# Numero e
np.e

In [ ]:
np.isfinite(np.e)

In [ ]:
np.isfinite(np.NINF)

In [ ]:
# Numero pi
np.pi