#### Fundamentos de tensorflow.

Vamos a aprender las nociones básicas de tensorflow

* Crear tensores
* Obtener info de tensores
* Manipular tensores
* Tensores & numpy
* usar @tf.function (una forma de acelerar las funciones de python)
* usar gpus 


### Los Tensores
los tensores son algo así como los arrays de NumPy, para los fines de este cuaderno y de ahora en adelante, puedes pensar en un tensor como una representación numérica multidimensional (también referida como n-dimensional, donde n puede ser cualquier número) de algo. Donde algo puede ser casi cualquier cosa que puedas imaginar:

- Podría ser los propios números (usando tensores para representar el precio de las casas).
- Podría ser una imagen (usando tensores para representar los píxeles de una imagen).
- Podría ser texto (usando tensores para representar palabras).
- O podría ser alguna otra forma de información (o datos) que quieras representar con números.

La principal diferencia entre los tensores y los arrays de NumPy (también un array n-dimensional de números) es que los tensores pueden utilizarse en GPUs (unidades de procesamiento gráfico) y TPUs (unidades de procesamiento tensorial).

La ventaja de poder ejecutarse en GPUs y TPUs es la computación más rápida, esto significa que si quisiéramos encontrar patrones en las representaciones numéricas de nuestros datos, generalmente podemos encontrarlos más rápido usando GPUs y TPUs.

Lo primero que haremos es importar TensorFlow bajo el alias común tf.


In [1]:
import tensorflow as tf
print(tf.__version__)

2.11.0


### Creando Tensores con tf.constant()

Como se mencionó anteriormente, en general, normalmente no crearás tensores tú mismo. Esto se debe a que TensorFlow tiene módulos integrados (como tf.io y tf.data) que son capaces de leer tus fuentes de datos y convertirlas automáticamente en tensores y luego, más adelante, los modelos de redes neuronales procesarán estos por nosotros.

Pero por ahora, porque estamos familiarizándonos con los tensores en sí mismos y cómo manipularlos, veremos cómo podemos crearlos nosotros mismos.

Comenzaremos usando `tf.constant()`

### Se puede crear un tensor escalar (sin dimensión):

In [2]:

scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#número de dimensiones
scalar.ndim


0

### Se puede crear un tensor vector (una dimensión):

In [4]:
#crear un vector
vector = tf.constant([10,10,10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [5]:
vector.ndim

1

### Se puede crear un tensor matriz (dos dimensiones):

In [6]:
#crear matrices
matriz=tf.constant([[10,3,3],[2,4,1]])
matriz

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  3,  3],
       [ 2,  4,  1]])>

In [7]:
matriz.ndim

2

Los tensores en TensorFlow pueden contener diversos tipos de datos, clasificados principalmente por su dtype (tipo de dato). Aquí se presenta una lista de los tipos de datos más comunes en TensorFlow:

- `tf.float32`: Punto flotante de 32 bits.
- `tf.float64`: Punto flotante de 64 bits, también conocido como `tf.double`.
- `tf.int8`: Entero de 8 bits.
- `tf.int16`: Entero de 16 bits.
- `tf.int32`: Entero de 32 bits.
- `tf.int64`: Entero de 64 bits, utilizado comúnmente para índices.
- `tf.uint8`: Entero sin signo de 8 bits.
- `tf.uint16`: Entero sin signo de 16 bits.
- `tf.uint32`: Entero sin signo de 32 bits.
- `tf.uint64`: Entero sin signo de 64 bits.
- `tf.bool`: Booleano.
- `tf.string`: Cadenas de texto.
- `tf.complex64`: Número complejo compuesto por dos floats de 32 bits.
- `tf.complex128`: Número complejo compuesto por dos floats de 64 bits, también conocido como `tf.double`.
- `tf.qint8`: Entero de 8 bits utilizado en cuantificación.
- `tf.qint16`: Entero de 16 bits utilizado en cuantificación.
- `tf.qint32`: Entero de 32 bits utilizado en cuantificación.
- `tf.quint8`: Entero sin signo de 8 bits utilizado en cuantificación.
- `tf.quint16`: Entero sin signo de 16 bits utilizado en cuantificación.

Estos tipos de datos permiten que TensorFlow maneje eficientemente una amplia gama de datos para diferentes tipos de operaciones, incluyendo cálculos matemáticos, manipulación de imágenes, procesamiento de texto, y mucho más.

podemos especificar el tipo de dato de los componentes del tensor, por ejemplo, float, con el parámetro dtype:


In [8]:
matriz2=tf.constant([[1,2,3],[5,2,3]],dtype=tf.float16)
matriz2

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [5., 2., 3.]], dtype=float16)>

### Se puede crear un tensor multidimensional:

In [9]:
#crear un tensor (3 o más dimensiones)
tensor=tf.constant([[[1,2],[2,3],[4,5]],
                    [[2,3],[1,5],[7,3]]])
tensor

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3],
        [4, 5]],

       [[2, 3],
        [1, 5],
        [7, 3]]])>

In [10]:
tensor.ndim  #2 matrices, de tres vectores, de dos posiciones cada uno

3

El ejemplo anterior también se conoce como un tensor de rango 3 (3 dimensiones), sin embargo, un tensor puede tener una cantidad arbitraria (ilimitada) de dimensiones.

Por ejemplo, podrías convertir una serie de imágenes en tensores con forma (224, 224, 3, 32), donde:
* 224, 224 (las primeras 2 dimensiones) son la altura y anchura de las imágenes en píxeles.
* 3 es el número de canales de color de la imagen (rojo, verde, azul).
* 32 es el tamaño del lote (el número de imágenes que una red neuronal ve en un momento dado).

Todas las variables anteriores que hemos creado son en realidad tensores. Pero también puedes escucharlas referidas con sus diferentes nombres (los que les dimos):
* **escalar**: un solo número.
* **vector**: un número con dirección (por ejemplo, velocidad del viento con dirección).
* **matriz**: un array bidimensional de números.
* **tensor**: un array de números n-dimensional (donde n puede ser cualquier número, un tensor de 0 dimensiones es un escalar, un tensor de 1 dimensión es un vector).

Para añadir a la confusión, los términos matriz y tensor a menudo se usan indistintamente.

En adelante, dado que estamos utilizando TensorFlow, todo lo que nos referimos y usamos serán tensores.

Para más información sobre la diferencia matemática entre escalares, vectores y matrices, consulta la [publicación de álgebra visual de Math is Fun](https://www.mathsisfun.com/algebra/scalar-vector-matrix.html).


### crear tensores con `tf.Variable`
- https://www.tensorflow.org/api_docs/python/tf/Variable

También puedes (aunque raramente lo harás, porque cuando trabajas con datos, los tensores se crean automáticamente) crear tensores usando [`tf.Variable()`](https://www.tensorflow.org/api_docs/python/tf/Variable).

La diferencia entre `tf.Variable()` y `tf.constant()` es que los tensores creados con `tf.constant()` son inmutables (no pueden cambiarse, solo pueden usarse para crear un nuevo tensor), mientras que, los tensores creados con `tf.Variable()` son mutables (pueden cambiarse).

### Manipulando tensores `tf.Variable`

Los tensores creados con `tf.Variable()` pueden ser modificados en su lugar utilizando métodos tales como:

* [`.assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) - asigna un valor diferente a un índice particular de un tensor variable.
* [`.add_assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add) - añade a un valor existente y lo reasigna en un índice particular de un tensor variable.


In [11]:
tensor_mutable=tf.Variable([10,7])
tensor_nomutable=tf.constant([10,7])
tensor_mutable,tensor_nomutable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [13]:
# cambiar uno de los elementos en un mutable -> ERROR!
tensor_mutable[0]=5

TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
# hay que usar assign
tensor_mutable[0].assign(5)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 7])>

In [16]:
#no se puede usar assign en un tensor constante
tensor_nomutable[0].assign(5)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [71]:
# Crear una variable tensor y asignar valores
I = tf.Variable(np.arange(0, 5))
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [72]:
#añadir 10 a todos los valores
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

## crear tensores aleatorios
#### tf.random.uniform y tf.random.normal 

Los tensores aleatorios son tensores de algún tamaño arbitrario que contienen números aleatorios.

¿Por qué querrías crear tensores aleatorios?

Esto es lo que las redes neuronales utilizan para inicializar sus pesos (patrones) que están intentando aprender en los datos.

Por ejemplo, el proceso de aprendizaje de una red neuronal a menudo implica tomar un array n-dimensional aleatorio de números y refinarlos hasta que representen algún tipo de patrón (una manera comprimida de representar los datos originales).


In [17]:
random_1 = tf.random.Generator.from_seed(42) # semilla para 'reproducibilidad'
random_1 = random_1.normal(shape=(3, 2)) # crear un tensor desde la distribución normal
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# son iguales?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
# mezclar un tensor
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# diferentes resultados cada vez
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [19]:
#crear utilizando semilla
random1=tf.random.Generator.from_seed(50)
tensor1=random1.normal(shape=(3,2))
tensor1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.45331386,  1.1487608 ],
       [-1.2659091 , -0.47450137],
       [ 2.006022  ,  0.28288034]], dtype=float32)>

In [20]:
#mezclar utilizando semilla
tensor1=tf.random.shuffle(tensor1,seed=42)
tensor1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 2.006022  ,  0.28288034],
       [-1.2659091 , -0.47450137],
       [ 0.45331386,  1.1487608 ]], dtype=float32)>

Prueba a ejecutar la celda anterior varias veces, ¿Por qué no sale siempre el mismo orden?

Es debido a la regla #4 de la documentación de [`tf.random.set_seed()`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed).

> "4. Si se establecen tanto la semilla global como la semilla de la operación: Ambas semillas se utilizan en conjunto para determinar la secuencia aleatoria."

`tf.random.set_seed(42)` establece la semilla global, y el parámetro `seed` en `tf.random.shuffle(seed=42)` establece la semilla de la operación.

Porque, "Las operaciones que dependen de una semilla aleatoria en realidad la derivan de dos semillas: las semillas global y de nivel de operación."


In [21]:
# mezclar siempre en el mismo orden

#global random seed
tf.random.set_seed(42)

# random seed de la operación
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [22]:
# establece la semilla global
tf.random.set_seed(42) # si comentas esto, obtienes siempre resultados diferentes

#se usa solo la semilla global
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

### Otras formas de crear tensores

Aunque raramente las uses (recuerda, muchas operaciones de tensores se realizan detrás de escena por ti), puedes usar [`tf.ones()`](https://www.tensorflow.org/api_docs/python/tf/ones) para crear un tensor de unos y [`tf.zeros()`](https://www.tensorflow.org/api_docs/python/tf/zeros) para crear un tensor de ceros.


In [23]:
tf.ones(shape=(3, 2))


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [24]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

También puedes convertir arrays de NumPy en tensores.

Recuerda, la principal diferencia entre los tensores y los arrays de NumPy es que los tensores pueden ejecutarse en GPUs.

🔑 Nota: Una matriz o tensor típicamente se representa por una letra mayúscula (por ejemplo, X o A) mientras que un vector se representa típicamente por una letra minúscula (por ejemplo, y o b).


In [25]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # crear un array de numpy
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # nota: la forma total (2*4*3) tiene que casar con el número de elementos del array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

### Obteniendo información de los tensores (forma, rango, tamaño)
Habrá momentos en los que querrás obtener diferentes piezas de información de tus tensores, en particular, debes conocer el siguiente vocabulario sobre tensores:

- **Forma (shape)**: La longitud (número de elementos) de cada una de las dimensiones de un tensor.
- **Rango (rank) **: El número de dimensiones de un tensor. Un escalar tiene rango 0, un vector tiene rango 1, una matriz tiene rango 2, un tensor tiene rango n.
- **Eje o Dimensión (axis) **: Una dimensión particular de un tensor.
- **Tamaño (size)**: El número total de elementos en el tensor.

Especialmente utilizarás estos cuando estés intentando alinear las formas de tus datos con las formas de tu modelo. Por ejemplo, asegurándote de que la forma de tus tensores de imagen sea la misma que la forma de la capa de entrada de tu modelo.



In [26]:
# Create un tensor de rango 4  (4 dimensiones)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
print("tipo de datos de cada elemento:", rank_4_tensor.dtype)
print("número de dimensiones (rank):", rank_4_tensor.ndim)
print("Forma del tensor:", rank_4_tensor.shape)
print("Elementos del eje 0 del tensor:", rank_4_tensor.shape[0])
print("Elementos del último eje del tensor:", rank_4_tensor.shape[-1])
print("Número total de elementos (2*3*4*5):", tf.size(rank_4_tensor).numpy()) 

tipo de datos de cada elemento: <dtype: 'float32'>
número de dimensiones (rank): 4
Forma del tensor: (2, 3, 4, 5)
Elementos del eje 0 del tensor: 2
Elementos del último eje del tensor: 5
Número total de elementos (2*3*4*5): 120


Se pueden indexar tensores como en numpy

In [29]:
# dame los dos primeros elementos de cada dimensión
rank_4_tensor[:2, :2, :2, :2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Obtener el último elemento de cada fila
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

También puedes añadir dimensiones a tu tensor mientras mantienes la misma información presente usando `tf.newaxis`.

In [31]:
# añadir una nueva dimensión (al final)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # en Python "..." significa "todas las dimensiones previas"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>)

esto también se puede hacer con `tf.expand_dims()`

In [32]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" significa último eje

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

## Manipulando tensores (operaciones con tensores)

Encontrar patrones en tensores (representación numérica de los datos) requiere manipularlos.

De nuevo, cuando construyes modelos en TensorFlow, gran parte de este descubrimiento de patrones se hace por ti.

### Operaciones básicas

Puedes realizar muchas de las operaciones matemáticas básicas directamente en tensores usando operadores de Python, tales como, `+`, `-`, `*`.


In [33]:
#suma
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [34]:
#multiplicación (elemento a elemento)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [35]:
#resta
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [36]:
# multiply, idéntico a '*' 
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [37]:
# los tensores originales no se cambian cuando se utilizan estos operadores
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

### Multiplicación de matrices

Una de las operaciones más comunes en los algoritmos de aprendizaje automático es la [multiplicación de matrices](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

TensorFlow implementa esta funcionalidad de multiplicación de matrices en el método [`tf.matmul()`](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul).

Las dos reglas principales para recordar sobre la multiplicación de matrices son:
1. Las dimensiones internas deben coincidir:
  * `(3, 5) @ (3, 5)` no funcionará
  * `(5, 3) @ (3, 5)` funcionará
  * `(3, 5) @ (5, 3)` funcionará
2. La matriz resultante tiene la forma de las dimensiones exteriores:
 * `(5, 3) @ (3, 5)` -> `(5, 5)`
 * `(3, 5) @ (5, 3)` -> `(3, 3)`

> 🔑 **Nota:** '`@`' en Python es el símbolo para la multiplicación de matrices.


In [38]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [39]:
# idéntico al anterior
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

La multiplicación anterior funcionaba porque los dos eran tensores de 2,2, si creamos de dimensiones incompatibles:


In [40]:
#  (3, 2) 
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

#  (3, 2) 
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [41]:
X @ Y #error!

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

Intentar multiplicar matrices de dos tensores con forma `(3, 2)` genera errores porque las dimensiones internas no coinciden.

Necesitamos:
* Cambiar la forma de X a `(2, 3)` para que sea `(2, 3) @ (3, 2)`.
* Cambiar la forma de Y a `(3, 2)` para que sea `(3, 2) @ (2, 3)`.

Podemos hacer esto con:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - nos permite cambiar la forma de un tensor a una forma definida.
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - cambia las dimensiones de un tensor dado.

![alineando dimensiones para el producto de matrices (dot product)](https://www.mathsisfun.com/algebra/images/matrix-multiply-b.svg)

Probemos primero `tf.reshape()`.


In [42]:
#recuerda
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [43]:
tf.reshape(Y, shape=(2, 3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [44]:
X @ tf.reshape(Y, shape=(2, 3))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

Funcionó, intentemos lo mismo con un `X` reconfigurado, excepto que esta vez usaremos [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) y `tf.matmul()`.

In [45]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [46]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

Se puede obtener el mismo resultado con:

In [47]:
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

Observa la diferencia en las formas resultantes al transponer `X` o reconfigurar `Y`.

Esto se debe a la 2da regla mencionada anteriormente:
 * `(3, 2) @ (2, 3)` -> `(3, 3)` hecho con `X @ tf.reshape(Y, shape=(2, 3))` 
 * `(2, 3) @ (3, 2)` -> `(2, 2)` hecho con `tf.matmul(tf.transpose(X), Y)`

Este tipo de manipulación de datos es un recordatorio: pasarás mucho de tu tiempo en el aprendizaje automático y trabajando con redes neuronales reconfigurando datos (en forma de tensores) para prepararlos para ser usados con varias operaciones (como alimentarlos a un modelo).

### El dot product (producto punto)

Multiplicar matrices de forma genérica también se conoce como el producto punto.

Puedes realizar la operación `tf.matmul()` usando [`tf.tensordot()`](https://www.tensorflow.org/api_docs/python/tf/tensordot).

`tf.tensordot()`:

Permite realizar el producto punto entre tensores, especificando los ejes sobre los cuales se quiere realizar la operación.
Es más flexible ya que puedes especificar los ejes a lo largo de los cuales el producto punto debe ser calculado. Esto significa que `tf.tensordot()` puede ser usado no solo para la multiplicación de matrices, sino también para operaciones más generales de producto punto.
Puede manejar tensores de cualquier rango, y los ejes a lo largo de los cuales se realiza el producto punto pueden ser configurados, permitiendo así una gama más amplia de operaciones de álgebra tensorial más allá de la simple multiplicación de matrices.

Las operaciones de producto punto (dot product) son fundamentales en álgebra lineal y tienen varias aplicaciones importantes, especialmente en el campo del aprendizaje automático y el procesamiento de señales. Aquí se describen varios tipos de operaciones de producto punto:
1. **Producto Punto Escalar (Scalar Dot Product):**
   - Este es el caso más simple y se aplica a vectores de la misma dimensión. El resultado es un escalar. Por ejemplo, el producto punto de dos vectores `a` y `b` se calcula como:
   
     $$
     \sum_{i=1}^{n} a_i b_i
     $$

2. **Multiplicación de Matrices (Matrix Multiplication):**
   - Es una generalización del producto punto escalar a matrices. Si tienes dos matrices, A de tamaño $$ m \times n $$ y B de tamaño $$ n \times p $$, el resultado es una nueva matriz C de tamaño $$ m \times p $$, donde cada elemento $$ C_{ij} $$ es el producto punto de la fila i de  A y la columna  j de  B:

     $$
     C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}
     $$

3. **Producto Tensorial (Tensor Dot Product):**
   - Esta operación extiende el concepto de producto punto a tensores de orden superior. En el contexto de tensores, el producto punto puede realizarse a lo largo de uno o más ejes especificados. Por ejemplo, si tienes dos tensores tridimensionales, puedes calcular el producto punto a lo largo de un eje particular, combinando las dimensiones correspondientes de cada tensor.


4. **Producto Punto Interno (Inner Product):**
   - Es similar al producto punto escalar, pero se usa en el contexto de espacios de dimensión superior. En matemáticas, el producto interior generaliza el concepto de producto punto a espacios vectoriales de dimensiones más altas.

     $$
     \langle \mathbf{a}, \mathbf{b} \rangle = \sum_{i=1}^{n} a_i b_i
     $$

5. **Producto Punto Externo (Outer Product):**
   - A diferencia del producto punto que produce un escalar (en el caso de vectores) o una matriz (en el caso de matrices), el producto externo toma dos vectores y produce una matriz. Si tienes dos vectores `a` y `b`, el producto externo es una matriz donde cada elemento es:

     $$
     C_{ij} = a_i b_j
     $$

6. **Convolution:**
   - Aunque no es un producto punto en el sentido tradicional, la convolución en el procesamiento de señales y en redes neuronales convolucionales se puede conceptualizar como una operación de producto punto entre filtros y segmentos de la señal o imagen, especialmente cuando se implementa mediante operaciones de matriz.

Cada uno de estos tipos de operaciones de producto punto tiene aplicaciones específicas y se elige en función del problema a resolver, la naturaleza de los datos y los objetivos del análisis o del modelo de aprendizaje automático.



In [48]:
# Realiza el producto X e Y (requiere la traspuesta de X)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

### Cambiando el tipo de dato de un tensor

A veces querrás alterar el tipo de dato predeterminado de tu tensor.

Esto es común cuando quieres computar usando menos precisión (por ejemplo, números de punto flotante de 16 bits vs. números de punto flotante de 32 bits).

Computar con menos precisión es útil en dispositivos con menor capacidad de cómputo como dispositivos móviles (porque menos bits, requieren menos espacio en las computaciones).

Puedes cambiar el tipo de dato de un tensor usando [`tf.cast()`](https://www.tensorflow.org/api_docs/python/tf/cast).


In [49]:
# Crear un tensor con tipo por defecto (float32)
B = tf.constant([1.7, 7.4])

# Crear un tensor con tipo por defecto(int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>)

In [50]:
# de float32 a float16 (precisión reducida)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [51]:
# int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

### Obteniendo el valor absoluto
A veces querrás los valores absolutos (todos los valores son positivos) de los elementos en tus tensores.

Para hacerlo, puedes usar [`tf.abs()`](https://www.tensorflow.org/api_docs/python/tf/math/abs).



In [52]:
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

### Encontrando el mínimo, máximo, media, suma (agregación)

Es posible agregar (realizar un cálculo en todo un tensor) tensores para encontrar cosas como el valor mínimo, valor máximo, media y suma de todos los elementos.

Para hacerlo, los métodos de agregación típicamente tienen la sintaxis `reduce()_[acción]`, tales como:
* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - encontrar el valor mínimo en un tensor.
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - encontrar el valor máximo en un tensor (útil cuando quieres encontrar la probabilidad de predicción más alta).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) - encontrar la media de todos los elementos en un tensor.
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) - encontrar la suma de todos los elementos en un tensor.
* **Nota:** típicamente, cada uno de estos está bajo el módulo `math`, por ejemplo, `tf.math.reduce_min()` pero puedes usar el alias `tf.reduce_min()`.

Veámoslos en acción.


In [53]:
# tensor con 50 valores random entre 0 y 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 2, 46, 25, 57, 86, 62, 57, 30, 65, 58, 83, 57, 18, 95, 33,  0, 82,
       22, 44, 84,  0, 99, 86, 56, 23, 86,  6, 95, 60, 63, 87, 40, 20, 83,
       72, 64, 32,  1, 94, 67, 72, 26, 45, 81, 62, 49, 73, 83, 70, 44])>

In [54]:
# mínimo
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [55]:
#máximo
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [56]:
#media
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=54>

In [57]:
#suma
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2745>

También puedes calcular la desviación estándar ([`tf.reduce_std()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_std)) y la varianza ([`tf.reduce_variance()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_variance)) de los elementos en un tensor usando métodos similares.

### Encontrando el máximo y mínimo posicional

¿Y cónmo se busca la posición en un tensor donde está el valor máximo?

Esto es útil cuando quieres alinear tus etiquetas (digamos `['Verde', 'Azul', 'Rojo']`) con tu tensor de probabilidades de predicción (por ejemplo, `[0.98, 0.01, 0.01]`).

En este caso, la etiqueta predicha (la que tiene la probabilidad de predicción más alta) sería `'Verde'`.

Puedes hacer lo mismo para el mínimo (si es necesario) con lo siguiente:
* [`tf.argmax()`](https://www.tensorflow.org/api_docs/python/tf/math/argmax) - encontrar la posición del elemento máximo en un tensor dado.
* [`tf.argmin()`](https://www.tensorflow.org/api_docs/python/tf/math/argmin) - encontrar la posición del elemento mínimo en un tensor dado.


In [58]:
# crear un tensor con 50 valores entre 0 y 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.72353716, 0.40246822, 0.83161408, 0.18778498, 0.59395943,
       0.13271066, 0.51486337, 0.96825219, 0.35256278, 0.18844455,
       0.02418701, 0.73970864, 0.29409647, 0.56235161, 0.19198946,
       0.47516714, 0.5799864 , 0.41018299, 0.41333635, 0.70265714,
       0.49633263, 0.54030857, 0.82307685, 0.04836412, 0.0091889 ,
       0.07678453, 0.64558563, 0.05141719, 0.99844597, 0.91875711,
       0.54139259, 0.53916083, 0.8578127 , 0.2051635 , 0.00872412,
       0.22493663, 0.83131279, 0.89433529, 0.42100545, 0.26250721,
       0.31896887, 0.17471295, 0.82056182, 0.26470344, 0.93565609,
       0.61338234, 0.17960954, 0.45824037, 0.16195915, 0.78934159])>

In [59]:
# buscar la posición del elemento máximo de F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=28>

In [60]:
# buscar la posición del elemento mínimo de F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=34>

In [61]:
# Encuentra la posición del elemento máximo de F
print(f"La posición del valor máximo de F es: {tf.argmax(F).numpy()}") 
print(f"El valor máximo de F es: {tf.reduce_max(F).numpy()}") 
print(f"Usando tf.argmax() para indexar F, el valor máximo de F es: {F[tf.argmax(F)].numpy()}")
print(f"¿Son los dos valores máximos iguales (deberían serlo)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")


La posición del valor máximo de F es: 28
El valor máximo de F es: 0.9984459657426845
Usando tf.argmax() para indexar F, el valor máximo de F es: 0.9984459657426845
¿Son los dos valores máximos iguales (deberían serlo)? True


### Comprimiendo un tensor (eliminando todas las dimensiones unitarias)

Si necesitas eliminar las dimensiones unitarias de un tensor (dimensiones de tamaño 1), puedes usar `tf.squeeze()`.

* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - elimina todas las dimensiones de 1 de un tensor.


In [62]:
# Crear un tensor de rango 5 con números entre 0 y 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [63]:
# Squeeze G (eliminar todas las dimensiones 1)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

### Codificación one-hot

Si tienes un tensor de índices y te gustaría codificarlo en one-hot, puedes usar [`tf.one_hot()`](https://www.tensorflow.org/api_docs/python/tf/one_hot).

También deberías especificar el parámetro `depth` (el nivel al que quieres codificar en one-hot).


In [64]:
# Crear una lista de índices
some_list = [0, 1, 2, 3]

# codificarlos en One hot
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [65]:
# Especificar valores personalizados para on y off 
tf.one_hot(some_list, depth=4, on_value="activo!", off_value="inactivo!")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'activo!', b'inactivo!', b'inactivo!', b'inactivo!'],
       [b'inactivo!', b'activo!', b'inactivo!', b'inactivo!'],
       [b'inactivo!', b'inactivo!', b'activo!', b'inactivo!'],
       [b'inactivo!', b'inactivo!', b'inactivo!', b'activo!']],
      dtype=object)>

### Operaciones matemáticas ( log, raiz cuadrada, cuadrado...)

Tensorflow también ofrece operaciones matemáticas como: 

* [`tf.square()`](https://www.tensorflow.org/api_docs/python/tf/math/square) - cuadrado de todos los valores de un tensor. 
* [`tf.sqrt()`](https://www.tensorflow.org/api_docs/python/tf/math/sqrt) - raíz cuadrada de todos los elementos de un tensor
* [`tf.math.log()`](https://www.tensorflow.org/api_docs/python/tf/math/log) - logaritmo de todos los elementos (base 10)

In [66]:
H = tf.constant(np.arange(1, 10))
print(tf.square(H))


tf.Tensor([ 1  4  9 16 25 36 49 64 81], shape=(9,), dtype=int32)


In [67]:
print(tf.sqrt(H)) #no debe ser entero


InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [69]:
# cast a float32
H = tf.cast(H, dtype=tf.float32)
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [70]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensores y NumPy

Hemos visto algunos ejemplos de cómo los tensores interactúan con los arrays de NumPy, por ejemplo, utilizando arrays de NumPy para crear tensores.

Los tensores también pueden ser convertidos a arrays de NumPy utilizando:

* `np.array()` - pasa un tensor para convertirlo en un ndarray (el tipo de dato principal de NumPy).
* `tensor.numpy()` - se llama en un tensor para convertirlo en un ndarray.

Hacer esto es útil ya que hace que los tensores sean iterables, así como también nos permite usar cualquiera de los métodos de NumPy en ellos.


In [74]:
#crear un tensor desde un array de numpy
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [75]:
# Convertir el tensor J a un np array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [76]:
# Convertir tensor J a NumPy con .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [77]:
# Crear un tensor desde NumPy y desde un array
numpy_J = tf.constant(np.array([3., 7., 10.])) # será float64 (por NumPy)
tensor_J = tf.constant([3., 7., 10.]) # será float32 (por defecto de Tensorflow)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Usando `@tf.function`

En tus aventuras con TensorFlow, podrías encontrarte con funciones de Python que tienen el decorador [`@tf.function`](https://www.tensorflow.org/api_docs/python/tf/function).

Si no estás seguro de qué hacen los decoradores de Python, [lee la guía de RealPython sobre ellos](https://realpython.com/primer-on-python-decorators/).

Pero en resumen, los decoradores modifican una función de una manera u otra.

En el caso del decorador `@tf.function`, convierte una función de Python en un grafo de TensorFlow llamable. Que es una forma elegante de decir, si has escrito tu propia función de Python, y la decoras con `@tf.function`, cuando exportas tu código (para potencialmente ejecutar en otro dispositivo), TensorFlow intentará convertirlo en una versión más rápida de sí mismo (haciéndola parte de un grafo de computación).

Para más información sobre esto, lee la guía [Mejor rendimiento con tf.function](https://www.tensorflow.org/guide/function).


In [78]:
# crear una función sencilla
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [79]:
# Crear la misma función con el decorador tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

## Encontrando acceso a GPUs

¿cómo se puede verificar si hay una disponible?

Puedes comprobar si tienes acceso a una GPU utilizando [`tf.config.list_physical_devices()`](https://www.tensorflow.org/guide/gpu).


In [80]:
print(tf.config.list_physical_devices('GPU'))

[]


In [81]:
!nvidia-smi

Thu Feb 15 07:43:00 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.70                 Driver Version: 537.70       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce MX350         WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P8              N/A / ERR! |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--



| **Hyperparameter** | **Typical value** |
| --- | --- |
| Input layer shape | Same shape as number of features (e.g. 3 for # bedrooms, # bathrooms, # car spaces in housing price prediction) |
| Hidden layer(s) | Problem specific, minimum = 1, maximum = unlimited |
| Neurons per hidden layer | Problem specific, generally 10 to 100 |
| Output layer shape | Same shape as desired prediction shape (e.g. 1 for house price) |
| Hidden activation | Usually [ReLU](https://www.kaggle.com/dansbecker/rectified-linear-units-relu-in-deep-learning) (rectified linear unit) |
| Output activation | None, ReLU, logistic/tanh |
| Loss function | [MSE](https://en.wikipedia.org/wiki/Mean_squared_error) (mean square error) or [MAE](https://en.wikipedia.org/wiki/Mean_absolute_error) (mean absolute error)/Huber (combination of MAE/MSE) if outliers |
| Optimizer | [SGD](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/SGD) (stochastic gradient descent), [Adam](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam) |

*Table 1: Typical architecture of a regression network. Source: Adapted from page 293 of [Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow Book by Aurélien Géron](https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/)*

> 🔑 **Nota:** Si tienes acceso a una GPU, automáticamente Tensorflow la usará cuando sea posible